<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <Platform>x64</Platform>
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\GLaDOS.Core\GLaDOS.Core.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="11.0.0-preview.4.26230.115" />
        <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.20.1" />
        <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.20.1" />
        <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.Managed" Version="0.6.0" />
        <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.DirectML" Version="0.6.0" />
    </ItemGroup>
</Project>
